server:
  port: 9109
spring:
  application:
    name: SECKILL
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.235.129:3306/dongyimaidb?useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.235.129 #mq的服务器地址
    username: guest #账号
    password: guest #密码
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.235.129
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000  #连接超时时间5秒
        readTimeout: 5000     #读超时时间5秒
#hystrix 配置
hystrix:
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 200
      queueSizeRejectionThreshold: 50
  command:
    default:
      execution:
        circuitBreaker:
          sleepWindowInMilliseconds: 100000
          forceClosed: true
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE
  shareSecurityContext: true
#位置支付交换机和队列
mq:
  pay:
    exchange:
      seckillorder: exchange.seckillorder
      seckillordertimer: exchange.seckillordertimer
    queue:
      seckillorder: queue.seckillorder
      seckillordertimer: queue.seckillordertimer
      seckillordertimerdelay: queue.seckillordertimerdelay
    routing:
      seckillorder: queue.seckillorder
# 配置sql打印日志
logging:
  level:
    com:
      offcn.seckill.listener: debug